# Generated by Django 2.0 on 2021-07-10 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='Email', max_length=255, unique=True)),
                ('password', models.CharField(default='Password', max_length=255)),
                ('role', models.CharField(default='Role', max_length=255)),
                ('fotp', models.IntegerField(default=123456)),
                ('Is_created', models.DateField(auto_now_add=True)),
                ('Is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='First Name', max_length=255)),
                ('lastname', models.CharField(default='Last Name', max_length=255)),
                ('address', models.CharField(default='Address', max_length=255)),
                ('bdate', models.DateField(null=True)),
                ('phone', models.BigIntegerField(default=1234567890)),
                ('gender', models.CharField(default='Gender', max_length=255)),
                ('marital', models.CharField(default='marital status', max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
            ],
        ),
        migrations.CreateModel(
            name='Hr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='First Name', max_length=255)),
                ('lastname', models.CharField(default='Last Name', max_length=255)),
                ('address', models.CharField(default='Address', max_length=255)),
                ('bdate', models.DateField(null=True)),
                ('phone', models.BigIntegerField(default=1234567890)),
                ('gender', models.CharField(default='Gender', max_length=255)),
                ('marital', models.CharField(default='marital status', max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Admin')),
            ],
        ),
    ]
